title: rm-rf.gg# ls -alh
baseurl: "/"
description: em....... //:\'<->'/ evi1m0 blog
#email: evi1m0.bat@gmail.com
author: evi1m0
avatar: "/static/imgs/992DB3B0-70D6-453F-8F39-EF89AA36A9BA.jpg"
profile: evi1m0.bat[at]gmail.com
twitter_username: evi1m0
github_username:  evi1m0
weibo_username: evi1m0
# Comment Service (Disqus or 多说)
disqus_shortname: evi1m0   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/
#permalink: /archivers/:title
gems:
- jekyll-paginate
- jekyll-gist
- jemoji

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
